---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-load-tester-config
  labels:
    app: nats-load-tester
    component: load-tester
data:
  config.default.json: |-
    {
      "load_test_specs": [
        {
          "name": "simple_high_throughput",
          "nats_url": "${NATS_URL}",
          "nats_creds_file": "${NATS_CREDS_MOUNT_PATH}/admin.creds",
          "use_jetstream": true,
          "client_id_prefix": "load_tester",
          "streams": [
            {
              "name_prefix": "load_stream",
              "count": 10,
              "replicas": 1,
              "subjects": [
                "test.subject.{}"
              ],
              "messages_per_stream_per_second": 10000000,
              "retention": "limits",
              "max_age": "2m",
              "storage": "file",
              "discard_new_per_subject": false,
              "discard": "old",
              "max_msgs": 100000000,
              "max_bytes": 2648576000,
              "max_msgs_per_subject": 100000000,
              "max_consumers": 1000000
            }
          ],
          "publishers": {
            "count_per_stream": 150,
            "stream_name_prefix": "load_stream",
            "publish_rate_per_second": 100000000,
            "publish_pattern": "steady",
            "publish_burst_size": 10,
            "message_size_bytes": 2048,
            "track_latency": true
          },
          "consumers": {
            "stream_name_prefix": "load_stream",
            "type": "push",
            "count_per_stream": 50,
            "durable_name_prefix": "load_consumer",
            "ack_wait_seconds": 5,
            "max_ack_pending": 1000,
            "consume_delay_ms": 500,
            "ack_policy": "explicit"
          },
          "behavior": {
            "duration_seconds": 30,
            "ramp_up_seconds": 0
          },
          "log_limits": {
            "max_lines": 50,
            "max_bytes": 16384
          }
        }
      ],
      "repeat_policy": {
        "enabled": true,
        "streams": {
          "count_multiplier": 1,
          "replicas_multiplier": 1,
          "messages_per_stream_per_second_multiplier": 1
        },
        "behavior": {
          "duration_multiplier": 1.2,
          "ramp_up_multiplier": 1
        },
        "consumers": {
          "ack_wait_multiplier": 1,
          "max_ack_pending_multiplier": 1,
          "consume_delay_multiplier": 1,
          "count_per_stream_multiplier": 1
        },
        "publishers": {
          "count_per_stream_multiplier": 1.2,
          "publish_rate_multiplier": 2,
          "message_size_bytes_multiplier": 1
        }
      },
      "storage": {
        "type": "badger",
        "path": "/var/lib/lt/load_test_stats.db"
      },
      "stats_collection_interval_seconds": 5
    }
