apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-load-tester
  labels:
    app: nats-load-tester
    component: load-tester
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nats-load-tester
      component: load-tester
  template:
    metadata:
      labels:
        app: nats-load-tester
        component: load-tester
    spec:
      containers:
      - name: load-tester
        image: ${DOCKER_REGISTRY}/nats-load-tester:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 9481
          name: http
          protocol: TCP
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: data
          mountPath: /var/lib/lt
        - name: nats-creds
          mountPath: ${NATS_CREDS_MOUNT_PATH}
          readOnly: true
        args:
        - "--use-default-config=true"
        - "--port=9481"
        - "--mode=both"
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: nats-load-tester-config
            optional: true
        - name: data
          emptyDir: {}
        - name: nats-creds
          secret:
            secretName: ${NATS_CREDS_SECRET_NAME}
