apiVersion: v1
kind: ConfigMap
metadata:
  name: ace-nats-config
  namespace: ace
data:
  nats.conf: |
    # NATS Clients Port
    port: 4222

    # PID file shared with configuration reloader.
    pid_file: "/var/run/nats/nats.pid"

    ###############
    #             #
    # Monitoring  #
    #             #
    ###############
    http: 8222
    server_name: $POD_NAME

    #####################
    #                   #
    # TLS Configuration #
    #                   #
    #####################
    tls {
      cert_file: /etc/nats-certs/clients/ace-cert/tls.crt
      key_file:  /etc/nats-certs/clients/ace-cert/tls.key
    }
    allow_non_tls: true

    ###################################
    #                                 #
    # NATS JetStream                  #
    #                                 #
    ###################################
    jetstream {
      max_mem: 1Gi
      store_dir: /nats/jetstream
      max_file:10Gi
    }

    ##################
    #               #
    # Cluster       #
    #               #
    ##################
    cluster {
      port: 6222
      name: "nats"

      routes = [
        "nats://ace-nats-0.ace-nats.ace.svc.cluster.local:6222",
        "nats://ace-nats-1.ace-nats.ace.svc.cluster.local:6222",
        "nats://ace-nats-2.ace-nats.ace.svc.cluster.local:6222"
      ]

      cluster_advertise: "$CLUSTER_ADVERTISE"
      connect_retries: 120
    }

    max_payload: 8MB
    lame_duck_grace_period: 10s
    lame_duck_duration: 30s

    ##################
    #                #
    # Websocket      #
    #                #
    ##################
    websocket {
      port: 443
      
      tls {
        cert_file: /etc/nats-certs/ws/ace-cert/tls.crt
        key_file:  /etc/nats-certs/ws/ace-cert/tls.key
      }
      same_origin: false
      allowed_origins: ["https://10.2.0.40"]
    }

    ##################
    #                #
    # Authorization  #
    #                #
    ##################
    operator: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJhdWQiOiJPREIzRlA2MlBHRFVQWFpLSjZXUTJFN05FM1RGTVBDNE01QUtDUEUzVEpHVlZMWElMQ0RTNDIzViIsImV4cCI6NDkxNDQ2NDcxMiwianRpIjoiUlRUMkFRQUpJNEwzWExFRkZaSU1TQkxYVlcyTEFTUzNZNEI2TTNXVkpHUkEyWFJaQlVCQSIsImlhdCI6MTc1ODc5MTExMiwiaXNzIjoiT0RCM0ZQNjJQR0RVUFhaS0o2V1EyRTdORTNURk1QQzRNNUFLQ1BFM1RKR1ZWTFhJTENEUzQyM1YiLCJuYW1lIjoiT3BlcmF0b3IiLCJuYmYiOjE3NTg3OTExMTIsInN1YiI6Ik9EQjNGUDYyUEdEVVBYWktKNldRMkU3TkUzVEZNUEM0TTVBS0NQRTNUSkdWVkxYSUxDRFM0MjNWIiwibmF0cyI6eyJzaWduaW5nX2tleXMiOlsiT0RCM0ZQNjJQR0RVUFhaS0o2V1EyRTdORTNURk1QQzRNNUFLQ1BFM1RKR1ZWTFhJTENEUzQyM1YiXSwidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.9l1DTd_fTer2DJ9uMEgwelwY5LWvl4ugnoy8gOfwPrQtkWTr26de2u7flAxhVF3JbTopM9tGHMNts4JWd_ElCg
    system_account: "AD3KCKIS7KZCWE7GUIDWNYG2K45LNOQTIPIDYXJCYESMZ5BEJUAEBPWF"

    resolver: {
      type: full
      dir: "/etc/nats-config/accounts/jwt"
      allow_delete: false
      interval: "2m"
    }
    resolver_preload: {"ABXJPMZ5T7GMSLWAJHXNCMLFDL5RMANRQGDC5CGXFNBRRU73R6U6X4XL":"eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiI2VEVXS0xMUTNGS0pKQldYRkFBUFJHTVFLRlhKWDY3NExENUtWRjY0WVhEWFVWN0xVV0hRIiwiaWF0IjoxNzU4NzkxMTEyLCJpc3MiOiJPREIzRlA2MlBHRFVQWFpLSjZXUTJFN05FM1RGTVBDNE01QUtDUEUzVEpHVlZMWElMQ0RTNDIzViIsIm5hbWUiOiJBZG1pbiIsInN1YiI6IkFCWEpQTVo1VDdHTVNMV0FKSFhOQ01MRkRMNVJNQU5SUUdEQzVDR1hGTkJSUlU3M1I2VTZYNFhMIiwibmF0cyI6eyJsaW1pdHMiOnsic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwiaW1wb3J0cyI6LTEsImV4cG9ydHMiOi0xLCJ3aWxkY2FyZHMiOnRydWUsImNvbm4iOi0xLCJsZWFmIjotMSwibWVtX3N0b3JhZ2UiOi0xLCJkaXNrX3N0b3JhZ2UiOi0xLCJzdHJlYW1zIjotMSwiY29uc3VtZXIiOi0xfSwiZGVmYXVsdF9wZXJtaXNzaW9ucyI6eyJwdWIiOnt9LCJzdWIiOnt9fSwiYXV0aG9yaXphdGlvbiI6e30sInR5cGUiOiJhY2NvdW50IiwidmVyc2lvbiI6Mn19.EL1XroErPrU9dnxl-my_iVP5L0AK04Hco4xnlVIz913wSPUfwF9r7wESakApKaXRIDMkkwojloQKjoyd9BnnAA","AD3KCKIS7KZCWE7GUIDWNYG2K45LNOQTIPIDYXJCYESMZ5BEJUAEBPWF":"eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJJRlFXSE83UVNIS0Q2QkpGMzZGU1RVQktMSFNBRzNMSlRDWjJKSkwyT1lQTlI2SUxES01BIiwiaWF0IjoxNzU4NzkxMTEyLCJpc3MiOiJPREIzRlA2MlBHRFVQWFpLSjZXUTJFN05FM1RGTVBDNE01QUtDUEUzVEpHVlZMWElMQ0RTNDIzViIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBRDNLQ0tJUzdLWkNXRTdHVUlEV05ZRzJLNDVMTk9RVElQSURZWEpDWUVTTVo1QkVKVUFFQlBXRiIsIm5hdHMiOnsibGltaXRzIjp7InN1YnMiOi0xLCJkYXRhIjotMSwicGF5bG9hZCI6LTEsImltcG9ydHMiOi0xLCJleHBvcnRzIjotMSwid2lsZGNhcmRzIjp0cnVlLCJjb25uIjotMSwibGVhZiI6LTF9LCJkZWZhdWx0X3Blcm1pc3Npb25zIjp7InB1YiI6e30sInN1YiI6e319LCJhdXRob3JpemF0aW9uIjp7fSwidHlwZSI6ImFjY291bnQiLCJ2ZXJzaW9uIjoyfX0.K6fKFA1e-ld68XEmHMvNcToW04EFYQIXBkUAB-OBk5dJdCAFWyGN4A-iJlLyvDTp92ahm5X77Og9funHK4dVAw"}
    system_account: "AD3KCKIS7KZCWE7GUIDWNYG2K45LNOQTIPIDYXJCYESMZ5BEJUAEBPWF"